@extends('site.layout')


@section('content_out')
<div class="jumbotron text-white banner" style="border:none; background-color: #20bf6b; border-radius:0px">
        <div class="container">
          <h1 class="display-3">Jardim dos Vagalumes (Garden of Fireflies Farm)</h1>
        </div>
      </div>
@endsection



@section('content')

<div class="row">
  <div class="col-sm-12">
    
<div><p class="c16"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 137.42px; height: 69.35px;"><img alt="" src="/images/image25.png" style="width: 137.42px; height: 69.35px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p></div><p class="c0 c4"><span class="c2"></span></p><p class="c0"><span class="c3 c5">&quot;Jardim dos Vagalumes&quot; (</span><span class="c7 c10 c5">Garden of Fireflies Farm)</span></p><p class="c0"><span class="c3 c5">The Garden of Fireflies is located at the rural area of Mogi das Cruzes City, within the metropolis of S&atilde;o Paulo, and about 70 km from the city of S&atilde;o Paulo. It is a family farm of 14.5 ha which has been</span><span class="c6">&nbsp;</span><span class="c3 c5">producing </span><span class="c7 c5">bamboo shoot processed food and bamboo craft products</span><span class="c3 c5">,</span><span class="c6">&nbsp;</span><span class="c2">among other products, for 3 generations. </span></p><p class="c0"><span class="c6 c5 c8">&nbsp;</span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 258.12px; height: 145.21px;"><img alt="Uma imagem contendo &aacute;rvore, ao ar livre, c&eacute;u, grama

Descri&ccedil;&atilde;o gerada com muito alta confian&ccedil;a" src="/images/image18.jpg" style="width: 258.12px; height: 145.21px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span class="c3">&nbsp;</span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 189.24px; height: 143.50px;"><img alt="Uma imagem contendo pessoa, posando, foto, em p&eacute;

Descri&ccedil;&atilde;o gerada com muito alta confian&ccedil;a" src="/images/image17.jpg" style="width: 189.24px; height: 143.50px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span style="overflow: hidden; display: inline-block; margin: 7.00px 3.65px; border: 0.00px solid #000000; transform: rotate(0.09rad) translateZ(0px); -webkit-transform: rotate(0.09rad) translateZ(0px); width: 159.97px; height: 88.67px;"><img alt="" src="/images/image2.png" style="width: 159.97px; height: 88.67px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p><p class="c0"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 82.95px; height: 147.48px;"><img alt="Uma imagem contendo grama, &aacute;rvore, ao ar livre, c&eacute;u

Descri&ccedil;&atilde;o gerada com muito alta confian&ccedil;a" src="/images/image20.jpg" style="width: 82.95px; height: 147.48px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span class="c3">&nbsp;</span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 216.84px; height: 144.50px;"><img alt="Uma imagem contendo mesa, interior, de madeira, ch&atilde;o

Descri&ccedil;&atilde;o gerada com alta confian&ccedil;a" src="/images/image19.jpg" style="width: 216.84px; height: 144.50px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span class="c3">&nbsp; &nbsp; &nbsp;</span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 250.40px; height: 140.86px;"><img alt="Uma imagem contendo ch&atilde;o, ao ar livre, pessoa, edif&iacute;cio

Descri&ccedil;&atilde;o gerada com muito alta confian&ccedil;a" src="/images/image22.jpg" style="width: 250.40px; height: 140.86px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p><p class="c0 c4"><span class="c2"></span></p><p class="c0"><span class="c7 c10 c5">Restaurant</span></p><p class="c1"><span class="c3 c5">Inside</span><span class="c6">&nbsp;</span><span class="c3 c5">the farm there is a restaurant whose menu has been developed with</span><span class="c6"><br></span><span class="c3 c5">some </span><span class="c5 c7">exclusive bamboo shoot based dishes</span><span class="c2">. Some of the dishes are family recipes, for example bamboo palm heart salad, bamboo shoot salt pie and Japanese recipes, and since 2017, some recipes have been developed exclusively by our Chef and contributors, like bamboo shoot risotto, bamboo shoot lasagna and deserts like bamboo sorbet and bamboo mousses. Because of this differential, our restaurant has been recognized by the bamboo specialists as innovative and unique in our category. </span></p><p class="c1"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 224.14px; height: 126.06px;"><img alt="https://www.jardimdosvagalumes.com.br/uploads/15591660871544034265116.jpg" src="/images/image21.jpg" style="width: 224.14px; height: 126.06px; margin-left: -0.00px; margin-top: -0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 173.80px; height: 126.59px;"><img alt="Uma imagem contendo pessoa

Descri&ccedil;&atilde;o gerada com alta confian&ccedil;a" src="/images/image26.jpg" style="width: 173.80px; height: 126.59px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span>&nbsp;</span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 94.52px; height: 126.08px;"><img alt="https://www.jardimdosvagalumes.com.br/uploads/1559166201WhatsApp%20Image%202019-01-27%20at%2012.16.59.jpeg" src="/images/image24.jpg" style="width: 94.52px; height: 126.08px; margin-left: -0.00px; margin-top: -0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 101.61px; height: 35.67px;"><img alt="" src="/images/image16.png" style="width: 101.61px; height: 35.67px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p><p class="c0"><span class="c3">&nbsp;</span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 129.08px; height: 96.81px;"><img alt="Uma imagem contendo comida, interior, arm&aacute;rio, mesa

Descri&ccedil;&atilde;o gerada com muito alta confian&ccedil;a" src="/images/image29.jpg" style="width: 129.08px; height: 96.81px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span class="c3">&nbsp; </span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 128.38px; height: 96.28px;"><img alt="Uma imagem contendo prato, comida, bolo, mesa

Descri&ccedil;&atilde;o gerada com muito alta confian&ccedil;a" src="/images/image27.jpg" style="width: 128.38px; height: 96.28px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span class="c3">&nbsp;</span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 126.97px; height: 95.22px;"><img alt="Uma imagem contendo comida, mesa, interior, prato

Descri&ccedil;&atilde;o gerada com muito alta confian&ccedil;a" src="/images/image28.jpg" style="width: 126.97px; height: 95.22px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span class="c3">&nbsp;</span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 65.46px; height: 87.28px;"><img alt="Uma imagem contendo prato, comida, mesa, interior

Descri&ccedil;&atilde;o gerada com muito alta confian&ccedil;a" src="/images/image30.jpg" style="width: 65.46px; height: 87.28px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 129.67px; height: 35.67px;"><img alt="" src="/images/image1.png" style="width: 129.67px; height: 35.67px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 106.33px; height: 41.64px;"><img alt="" src="/images/image40.png" style="width: 106.33px; height: 41.64px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 129.67px; height: 35.67px;"><img alt="" src="/images/image35.png" style="width: 129.67px; height: 35.67px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p><p class="c0"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 116.63px; height: 87.47px;"><img alt="Uma imagem contendo comida, prato, sobremesa, peda&ccedil;o

Descri&ccedil;&atilde;o gerada com muito alta confian&ccedil;a" src="/images/image31.jpg" style="width: 116.63px; height: 87.47px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 117.87px; height: 89.86px;"><img alt="Uma imagem contendo prato, mesa, comida, sentado

Descri&ccedil;&atilde;o gerada com muito alta confian&ccedil;a" src="/images/image33.jpg" style="width: 160.03px; height: 89.86px; margin-left: -21.05px; margin-top: -0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span class="c3">&nbsp;</span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 151.19px; height: 85.06px;"><img alt="Uma imagem contendo comida, mesa, interior, prato

Descri&ccedil;&atilde;o gerada com muito alta confian&ccedil;a" src="/images/image34.jpg" style="width: 151.19px; height: 85.06px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 129.67px; height: 35.67px;"><img alt="" src="/images/image4.png" style="width: 129.67px; height: 35.67px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 129.67px; height: 35.67px;"><img alt="" src="/images/image32.png" style="width: 129.67px; height: 35.67px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 76.33px; height: 51.67px;"><img alt="" src="/images/image6.png" style="width: 76.33px; height: 51.67px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p><p class="c0 c4"><span class="c2"></span></p><p class="c0"><span class="c7 c10 c5">Rural Tourism: linkage of Agro, Eco and Pedagogic Tourism based on bamboo knoledge</span></p><p class="c1"><span class="c3 c5">We also offer seminars and workshops about</span><span class="c6">&nbsp;</span><span class="c2">sustainability and bamboo processing with specialized guided-visit for guests and students. In our bamboo processing workshop, the guests and students are supposed to harvest bamboo shoots, learn how to process and cook, and then taste the bamboo shoot based dishes. In the Pegagogic Tourism, children learn about the environmental sustainability function of bamboo, bamboo made structures, eat bamboo shoot dishes and can play at a bamboo made playground.</span></p><p class="c0"><span style="overflow: hidden; display: inline-block; margin: 7.86px 4.18px; border: 0.00px solid #000000; transform: rotate(6.19rad) translateZ(0px); -webkit-transform: rotate(6.19rad) translateZ(0px); width: 182.69px; height: 102.78px;"><img alt="Uma imagem contendo &aacute;rvore, ao ar livre, grama, c&eacute;u

Descri&ccedil;&atilde;o gerada com muito alta confian&ccedil;a" src="/images/image36.jpg" style="width: 182.69px; height: 102.78px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 176.41px; height: 132.31px;"><img alt="Uma imagem contendo grama, planta, &aacute;rvore, bambu

Descri&ccedil;&atilde;o gerada com muito alta confian&ccedil;a" src="/images/image37.jpg" style="width: 176.41px; height: 132.31px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 177.77px; height: 133.33px;"><img alt="Uma imagem contendo &aacute;rvore, grama, ao ar livre, pessoa

Descri&ccedil;&atilde;o gerada com muito alta confian&ccedil;a" src="/images/image38.jpg" style="width: 177.77px; height: 133.33px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 177.69px; height: 133.27px;"><img alt="Uma imagem contendo pessoa, ao ar livre, pessoas, grupo

Descri&ccedil;&atilde;o gerada com muito alta confian&ccedil;a" src="/images/image39.jpg" style="width: 177.69px; height: 133.27px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 174.96px; height: 131.22px;"><img alt="Uma imagem contendo pessoa, ao ar livre, &aacute;rvore, em p&eacute;

Descri&ccedil;&atilde;o gerada com muito alta confian&ccedil;a" src="/images/image5.jpg" style="width: 174.96px; height: 131.22px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 197.93px; height: 111.35px;"><img alt="Uma imagem contendo mesa, interior, comida, x&iacute;cara

Descri&ccedil;&atilde;o gerada com muito alta confian&ccedil;a" src="/images/image7.jpg" style="width: 197.93px; height: 111.35px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p><p class="c14"><span class="c6 c5 c11">Agro-tourism with bamboo harvest-cooking workshop for 3</span><span class="c6 c11 c5 c13">rd</span><span class="c6 c10 c11 c5">&nbsp;age people</span></p><p class="c14 c4"><span class="c6 c10 c8 c5"></span></p><p class="c0 c4"><span class="c2"></span></p><p class="c0 c4"><span class="c2"></span></p><p class="c0"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 257.87px; height: 145.06px;"><img alt="Uma imagem contendo &aacute;rvore, ao ar livre, c&eacute;u, pessoa

Descri&ccedil;&atilde;o gerada com muito alta confian&ccedil;a" src="/images/image8.jpg" style="width: 257.87px; height: 145.06px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 232.65px; height: 145.99px;"><img alt="Uma imagem contendo grama, ao ar livre, &aacute;rvore, pessoa

Descri&ccedil;&atilde;o gerada com muito alta confian&ccedil;a" src="/images/image9.jpg" style="width: 304.97px; height: 171.55px; margin-left: -28.84px; margin-top: -0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 274.80px; height: 154.59px;"><img alt="Uma imagem contendo interior, mesa, pessoa, sentado

Descri&ccedil;&atilde;o gerada com muito alta confian&ccedil;a" src="/images/image10.jpg" style="width: 274.80px; height: 154.59px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 146.55px; height: 195.40px;"><img alt="Uma imagem contendo grama, ao ar livre, edif&iacute;cio, c&eacute;u

Descri&ccedil;&atilde;o gerada com muito alta confian&ccedil;a" src="/images/image11.jpg" style="width: 146.55px; height: 195.40px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span class="c2">&nbsp;</span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 135.40px; height: 110.82px;"><img alt="" src="/images/image3.png" style="width: 135.40px; height: 110.82px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p><p class="c0 c4"><span class="c2"></span></p><p class="c0"><span class="c7 c10 c5">About our Bamboos </span></p><p class="c1"><span class="c3 c5">We have about 5 ha of a bamboo grove with 4 species of bamboo: </span><span class="c3 c9">Phyllostachys aurea, P. pubescens, Dendrocalamus asper and D. asper</span><span class="c2">, brought from Asia by our ancestors. The bamboo forest in our land initially performed environmental protection in our land for more than 50 years: it covers all the area nearby the head-waters, playing functions of protection of our water source against soil erosion and lake silting. It surrounds the limits of the property, protecting against wind and strangers. It supplies food and wood for the family for 5 generations. Finally, nowadays, supplies us also with the raw material for our business production and our environmental seminars and ecotourism. &nbsp;</span></p><p class="c0"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 210.74px; height: 158.10px;"><img alt="" src="/images/image12.jpg" style="width: 210.74px; height: 158.10px; margin-left: -0.00px; margin-top: -0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 209.84px; height: 157.38px;"><img alt="Uma imagem contendo ao ar livre, &aacute;rvore, ch&atilde;o, grama

Descri&ccedil;&atilde;o gerada com muito alta confian&ccedil;a" src="/images/image13.jpg" style="width: 209.84px; height: 157.38px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 118.65px; height: 158.21px;"><img alt="Uma imagem contendo &aacute;rvore, ao ar livre, planta

Descri&ccedil;&atilde;o gerada com muito alta confian&ccedil;a" src="/images/image14.jpg" style="width: 118.65px; height: 158.21px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p><p class="c0"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 195.23px; height: 146.42px;"><img alt="Uma imagem contendo &aacute;rvore, ao ar livre, planta, grama

Descri&ccedil;&atilde;o gerada com muito alta confian&ccedil;a" src="/images/image15.jpg" style="width: 195.23px; height: 146.42px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 110.35px; height: 147.13px;"><img alt="Uma imagem contendo &aacute;rvore, ao ar livre, grama, floresta

Descri&ccedil;&atilde;o gerada com muito alta confian&ccedil;a" src="/images/image23.jpg" style="width: 110.35px; height: 147.13px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p><p class="c0 c4"><span class="c2"></span></p><p class="c0"><span class="c7 c5 c10">Future perspectives:</span></p><p class="c1"><span class="c3 c5">Our next plans for our farm are to enlarge our bamboo forest by planting an agroforest mixing</span><span class="c6">&nbsp;other </span><span class="c3 c5">bamboo species and commercial and native fruits trees, develop more</span><span class="c6"><br></span><span class="c3 c5">bamboo products, and construct the buildings and furniture of our property with bamboo culms. Simultaneously, we are creating a network with stakeholders, producers</span><span class="c6"><br></span><span class="c2">and processors of bamboo in our region, in Brazil and worldwide. </span></p><p class="c0"><span class="c3 c5">Our future aim is to be</span><span class="c6">&nbsp;</span><span class="c3 c5">reference in bamboo in our region, and keep working and more harder divulging to different audiences about the various possibilities and environmental services that this incredible plant offers us. &nbsp;</span><span class="c6"><br></span></p><p class="c0 c4" id="h.gjdgxs"><span class="c2"></span></p><p class="c0 c4"><span class="c2"></span></p><p class="c0 c4"><span class="c2"></span></p>










  </div>
</div>

   



@endsection
